name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup SSH
      uses: MrSquaare/ssh-setup-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        private-key: ${{ secrets.PRIVATE_KEY }}
    - name: Rsync deployments
      uses: contention/rsync-deployments@v1.0.0        
    - name: Upload static files
      run: |
          rsync -rav ./frontend/* ${{ secrets.EC2_INSTANCE_USER }}@${{ secrets.EC2_HOST }}:/opt/app/