name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Debug
      run: |
        ls -lah
        echo "Current dir: $(pwd ~/)"
        ls -lah /home/runner/work/slesh.dev
        ls -lah /home/runner/work/slesh.dev/slesh.dev
        ls -lah /home/runner/work/slesh.dev/slesh.dev/frontend
    - name: Deploy frontend
      uses: easingthemes/ssh-deploy@v2.1.5    
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rav"
        SOURCE: "frontend/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
        EXCLUDE: "frontend/dist/"